[package]
authors = ["RTR <k.teza1@gmail.com>"]
name = "mosquitto"
version = "0.3.0"

[dependencies]
lazy_static = "*"
libc = "*"
rand = "*"
chan = "*"
log = "0.3"

[dependencies.mosquitto-sys]
path = "mosquitto-sys"
version = "*"

[dev-dependencies]
env_logger = "0.3"